// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fir_filter_b.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fir_filter_b::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fir_filter_b::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> fir_filter_b::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<32> fir_filter_b::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool fir_filter_b::ap_const_boolean_1 = true;
const bool fir_filter_b::ap_const_boolean_0 = false;
const sc_lv<32> fir_filter_b::ap_const_lv32_FFFFFE27 = "11111111111111111111111000100111";
const sc_lv<32> fir_filter_b::ap_const_lv32_FFFFFE5F = "11111111111111111111111001011111";
const sc_lv<32> fir_filter_b::ap_const_lv32_FFFFFDF9 = "11111111111111111111110111111001";
const sc_lv<32> fir_filter_b::ap_const_lv32_FFFFFDD6 = "11111111111111111111110111010110";
const sc_lv<32> fir_filter_b::ap_const_lv32_FFFFFE1B = "11111111111111111111111000011011";
const sc_lv<32> fir_filter_b::ap_const_lv32_FFFFFEED = "11111111111111111111111011101101";
const sc_lv<32> fir_filter_b::ap_const_lv32_67 = "1100111";
const sc_lv<32> fir_filter_b::ap_const_lv32_294 = "1010010100";
const sc_lv<32> fir_filter_b::ap_const_lv32_56A = "10101101010";
const sc_lv<32> fir_filter_b::ap_const_lv32_8CC = "100011001100";
const sc_lv<32> fir_filter_b::ap_const_lv32_C83 = "110010000011";
const sc_lv<32> fir_filter_b::ap_const_lv32_104C = "1000001001100";
const sc_lv<32> fir_filter_b::ap_const_lv32_13D7 = "1001111010111";
const sc_lv<32> fir_filter_b::ap_const_lv32_16D5 = "1011011010101";
const sc_lv<32> fir_filter_b::ap_const_lv32_1901 = "1100100000001";
const sc_lv<32> fir_filter_b::ap_const_lv32_1A25 = "1101000100101";
const sc_lv<26> fir_filter_b::ap_const_lv26_3FFFE27 = "11111111111111111000100111";
const sc_lv<26> fir_filter_b::ap_const_lv26_3FFFE5F = "11111111111111111001011111";

fir_filter_b::fir_filter_b(sc_module_name name) : sc_module(name), mVcdFile(0) {
    d_conv_mul_mul_16bkb_U14 = new d_conv_mul_mul_16bkb<1,1,16,10,26>("d_conv_mul_mul_16bkb_U14");
    d_conv_mul_mul_16bkb_U14->din0(extLd4_loc_channel);
    d_conv_mul_mul_16bkb_U14->din1(mul_ln700_31_fu_765_p1);
    d_conv_mul_mul_16bkb_U14->dout(mul_ln700_31_fu_765_p2);
    d_conv_mul_mul_16cud_U15 = new d_conv_mul_mul_16cud<1,1,16,11,32>("d_conv_mul_mul_16cud_U15");
    d_conv_mul_mul_16cud_U15->din0(mul_ln700_29_fu_771_p0);
    d_conv_mul_mul_16cud_U15->din1(mul_ln700_29_fu_771_p1);
    d_conv_mul_mul_16cud_U15->dout(mul_ln700_29_fu_771_p2);
    d_conv_mac_muladddEe_U16 = new d_conv_mac_muladddEe<1,1,16,10,26,26>("d_conv_mac_muladddEe_U16");
    d_conv_mac_muladddEe_U16->din0(shift_reg_V_1_0_load_reg_934);
    d_conv_mac_muladddEe_U16->din1(grp_fu_777_p1);
    d_conv_mac_muladddEe_U16->din2(mul_ln700_31_reg_939);
    d_conv_mac_muladddEe_U16->dout(grp_fu_777_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln700_10_fu_660_p2);
    sensitive << ( mul_ln700_12_reg_844 );
    sensitive << ( mul_ln700_13_reg_849 );

    SC_METHOD(thread_add_ln700_11_fu_664_p2);
    sensitive << ( mul_ln700_14_reg_854 );
    sensitive << ( mul_ln700_15_reg_859 );

    SC_METHOD(thread_add_ln700_12_fu_668_p2);
    sensitive << ( add_ln700_10_fu_660_p2 );
    sensitive << ( add_ln700_11_fu_664_p2 );

    SC_METHOD(thread_add_ln700_13_fu_723_p2);
    sensitive << ( add_ln700_9_reg_959 );
    sensitive << ( add_ln700_12_reg_964 );

    SC_METHOD(thread_add_ln700_14_fu_727_p2);
    sensitive << ( add_ln700_6_fu_718_p2 );
    sensitive << ( add_ln700_13_fu_723_p2 );

    SC_METHOD(thread_add_ln700_15_fu_674_p2);
    sensitive << ( mul_ln700_16_reg_864 );
    sensitive << ( mul_ln700_17_reg_869 );

    SC_METHOD(thread_add_ln700_16_fu_678_p2);
    sensitive << ( mul_ln700_18_reg_874 );
    sensitive << ( mul_ln700_19_reg_879 );

    SC_METHOD(thread_add_ln700_17_fu_682_p2);
    sensitive << ( add_ln700_15_fu_674_p2 );
    sensitive << ( add_ln700_16_fu_678_p2 );

    SC_METHOD(thread_add_ln700_18_fu_688_p2);
    sensitive << ( mul_ln700_20_reg_884 );
    sensitive << ( mul_ln700_21_reg_889 );

    SC_METHOD(thread_add_ln700_19_fu_692_p2);
    sensitive << ( mul_ln700_22_reg_894 );
    sensitive << ( mul_ln700_23_reg_899 );

    SC_METHOD(thread_add_ln700_1_fu_628_p2);
    sensitive << ( mul_ln700_2_reg_794 );
    sensitive << ( mul_ln700_3_reg_799 );

    SC_METHOD(thread_add_ln700_20_fu_733_p2);
    sensitive << ( add_ln700_18_reg_974 );
    sensitive << ( add_ln700_19_reg_979 );

    SC_METHOD(thread_add_ln700_21_fu_737_p2);
    sensitive << ( add_ln700_17_reg_969 );
    sensitive << ( add_ln700_20_fu_733_p2 );

    SC_METHOD(thread_add_ln700_22_fu_696_p2);
    sensitive << ( mul_ln700_24_reg_904 );
    sensitive << ( mul_ln700_25_reg_909 );

    SC_METHOD(thread_add_ln700_23_fu_700_p2);
    sensitive << ( mul_ln700_26_reg_914 );
    sensitive << ( mul_ln700_27_reg_919 );

    SC_METHOD(thread_add_ln700_24_fu_704_p2);
    sensitive << ( add_ln700_22_fu_696_p2 );
    sensitive << ( add_ln700_23_fu_700_p2 );

    SC_METHOD(thread_add_ln700_25_fu_710_p2);
    sensitive << ( mul_ln700_28_reg_924 );
    sensitive << ( mul_ln700_29_fu_771_p2 );

    SC_METHOD(thread_add_ln700_27_fu_745_p2);
    sensitive << ( add_ln700_25_reg_989 );
    sensitive << ( sext_ln700_1_fu_742_p1 );

    SC_METHOD(thread_add_ln700_28_fu_750_p2);
    sensitive << ( add_ln700_24_reg_984 );
    sensitive << ( add_ln700_27_fu_745_p2 );

    SC_METHOD(thread_add_ln700_29_fu_755_p2);
    sensitive << ( add_ln700_21_reg_1004 );
    sensitive << ( add_ln700_28_reg_1009 );

    SC_METHOD(thread_add_ln700_2_fu_632_p2);
    sensitive << ( add_ln700_fu_624_p2 );
    sensitive << ( add_ln700_1_fu_628_p2 );

    SC_METHOD(thread_add_ln700_3_fu_638_p2);
    sensitive << ( mul_ln700_4_reg_804 );
    sensitive << ( mul_ln700_5_reg_809 );

    SC_METHOD(thread_add_ln700_4_fu_642_p2);
    sensitive << ( mul_ln700_6_reg_814 );
    sensitive << ( mul_ln700_7_reg_819 );

    SC_METHOD(thread_add_ln700_5_fu_714_p2);
    sensitive << ( add_ln700_3_reg_949 );
    sensitive << ( add_ln700_4_reg_954 );

    SC_METHOD(thread_add_ln700_6_fu_718_p2);
    sensitive << ( add_ln700_2_reg_944 );
    sensitive << ( add_ln700_5_fu_714_p2 );

    SC_METHOD(thread_add_ln700_7_fu_646_p2);
    sensitive << ( mul_ln700_8_reg_824 );
    sensitive << ( mul_ln700_9_reg_829 );

    SC_METHOD(thread_add_ln700_8_fu_650_p2);
    sensitive << ( mul_ln700_10_reg_834 );
    sensitive << ( mul_ln700_11_reg_839 );

    SC_METHOD(thread_add_ln700_9_fu_654_p2);
    sensitive << ( add_ln700_7_fu_646_p2 );
    sensitive << ( add_ln700_8_fu_650_p2 );

    SC_METHOD(thread_add_ln700_fu_624_p2);
    sensitive << ( mul_ln700_reg_784 );
    sensitive << ( mul_ln700_1_reg_789 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_idle_pp0_0to2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to2 );

    SC_METHOD(thread_grp_fu_777_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_10_fu_293_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_20 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_10_fu_293_p2);
    sensitive << ( mul_ln700_10_fu_293_p0 );

    SC_METHOD(thread_mul_ln700_11_fu_309_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_19 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_11_fu_309_p2);
    sensitive << ( mul_ln700_11_fu_309_p0 );

    SC_METHOD(thread_mul_ln700_12_fu_325_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_18 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_12_fu_325_p2);
    sensitive << ( mul_ln700_12_fu_325_p0 );

    SC_METHOD(thread_mul_ln700_13_fu_341_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_17 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_13_fu_341_p2);
    sensitive << ( mul_ln700_13_fu_341_p0 );

    SC_METHOD(thread_mul_ln700_14_fu_357_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_16 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_14_fu_357_p2);
    sensitive << ( mul_ln700_14_fu_357_p0 );

    SC_METHOD(thread_mul_ln700_15_fu_373_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_15 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_15_fu_373_p2);
    sensitive << ( mul_ln700_15_fu_373_p0 );

    SC_METHOD(thread_mul_ln700_16_fu_389_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_14 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_16_fu_389_p2);
    sensitive << ( mul_ln700_16_fu_389_p0 );

    SC_METHOD(thread_mul_ln700_17_fu_405_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_13 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_17_fu_405_p2);
    sensitive << ( mul_ln700_17_fu_405_p0 );

    SC_METHOD(thread_mul_ln700_18_fu_421_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_12 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_18_fu_421_p2);
    sensitive << ( mul_ln700_18_fu_421_p0 );

    SC_METHOD(thread_mul_ln700_19_fu_437_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_11 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_19_fu_437_p2);
    sensitive << ( mul_ln700_19_fu_437_p0 );

    SC_METHOD(thread_mul_ln700_1_fu_149_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_29 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_1_fu_149_p2);
    sensitive << ( mul_ln700_1_fu_149_p0 );

    SC_METHOD(thread_mul_ln700_20_fu_453_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_10 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_20_fu_453_p2);
    sensitive << ( mul_ln700_20_fu_453_p0 );

    SC_METHOD(thread_mul_ln700_21_fu_469_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_9 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_21_fu_469_p2);
    sensitive << ( mul_ln700_21_fu_469_p0 );

    SC_METHOD(thread_mul_ln700_22_fu_485_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_8 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_22_fu_485_p2);
    sensitive << ( mul_ln700_22_fu_485_p0 );

    SC_METHOD(thread_mul_ln700_23_fu_501_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_7 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_23_fu_501_p2);
    sensitive << ( mul_ln700_23_fu_501_p0 );

    SC_METHOD(thread_mul_ln700_24_fu_517_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_6 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_24_fu_517_p2);
    sensitive << ( mul_ln700_24_fu_517_p0 );

    SC_METHOD(thread_mul_ln700_25_fu_533_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_5 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_25_fu_533_p2);
    sensitive << ( mul_ln700_25_fu_533_p0 );

    SC_METHOD(thread_mul_ln700_26_fu_549_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_26_fu_549_p2);
    sensitive << ( mul_ln700_26_fu_549_p0 );

    SC_METHOD(thread_mul_ln700_27_fu_565_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_3 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_27_fu_565_p2);
    sensitive << ( mul_ln700_27_fu_565_p0 );

    SC_METHOD(thread_mul_ln700_28_fu_581_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_28_fu_581_p2);
    sensitive << ( mul_ln700_28_fu_581_p0 );

    SC_METHOD(thread_mul_ln700_29_fu_771_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sext_ln180_reg_929 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_29_fu_771_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_2_fu_165_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_28 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_2_fu_165_p2);
    sensitive << ( mul_ln700_2_fu_165_p0 );

    SC_METHOD(thread_mul_ln700_31_fu_765_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_3_fu_181_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_27 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_3_fu_181_p2);
    sensitive << ( mul_ln700_3_fu_181_p0 );

    SC_METHOD(thread_mul_ln700_4_fu_197_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_26 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_4_fu_197_p2);
    sensitive << ( mul_ln700_4_fu_197_p0 );

    SC_METHOD(thread_mul_ln700_5_fu_213_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_25 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_5_fu_213_p2);
    sensitive << ( mul_ln700_5_fu_213_p0 );

    SC_METHOD(thread_mul_ln700_6_fu_229_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_24 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_6_fu_229_p2);
    sensitive << ( mul_ln700_6_fu_229_p0 );

    SC_METHOD(thread_mul_ln700_7_fu_245_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_23 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_7_fu_245_p2);
    sensitive << ( mul_ln700_7_fu_245_p0 );

    SC_METHOD(thread_mul_ln700_8_fu_261_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_22 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_8_fu_261_p2);
    sensitive << ( mul_ln700_8_fu_261_p0 );

    SC_METHOD(thread_mul_ln700_9_fu_277_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_21 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_9_fu_277_p2);
    sensitive << ( mul_ln700_9_fu_277_p0 );

    SC_METHOD(thread_mul_ln700_fu_133_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_30 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_fu_133_p2);
    sensitive << ( mul_ln700_fu_133_p0 );

    SC_METHOD(thread_sext_ln180_fu_591_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( shift_reg_V_1_1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln180_fu_591_p1);
    sensitive << ( sext_ln180_fu_591_p0 );

    SC_METHOD(thread_sext_ln700_1_fu_742_p1);
    sensitive << ( add_ln700_26_reg_994 );

    SC_METHOD(thread_y_V);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( add_ln700_14_reg_999 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( add_ln700_29_fu_755_p2 );

    SC_METHOD(thread_y_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    shift_reg_V_1_30 = "00000000000000000000000000000000";
    shift_reg_V_1_29 = "00000000000000000000000000000000";
    shift_reg_V_1_28 = "00000000000000000000000000000000";
    shift_reg_V_1_27 = "00000000000000000000000000000000";
    shift_reg_V_1_26 = "00000000000000000000000000000000";
    shift_reg_V_1_25 = "00000000000000000000000000000000";
    shift_reg_V_1_24 = "00000000000000000000000000000000";
    shift_reg_V_1_23 = "00000000000000000000000000000000";
    shift_reg_V_1_22 = "00000000000000000000000000000000";
    shift_reg_V_1_21 = "00000000000000000000000000000000";
    shift_reg_V_1_20 = "00000000000000000000000000000000";
    shift_reg_V_1_19 = "00000000000000000000000000000000";
    shift_reg_V_1_18 = "00000000000000000000000000000000";
    shift_reg_V_1_17 = "00000000000000000000000000000000";
    shift_reg_V_1_16 = "00000000000000000000000000000000";
    shift_reg_V_1_15 = "00000000000000000000000000000000";
    shift_reg_V_1_14 = "00000000000000000000000000000000";
    shift_reg_V_1_13 = "00000000000000000000000000000000";
    shift_reg_V_1_12 = "00000000000000000000000000000000";
    shift_reg_V_1_11 = "00000000000000000000000000000000";
    shift_reg_V_1_10 = "00000000000000000000000000000000";
    shift_reg_V_1_9 = "00000000000000000000000000000000";
    shift_reg_V_1_8 = "00000000000000000000000000000000";
    shift_reg_V_1_7 = "00000000000000000000000000000000";
    shift_reg_V_1_6 = "00000000000000000000000000000000";
    shift_reg_V_1_5 = "00000000000000000000000000000000";
    shift_reg_V_1_4 = "00000000000000000000000000000000";
    shift_reg_V_1_3 = "00000000000000000000000000000000";
    shift_reg_V_1_2 = "00000000000000000000000000000000";
    shift_reg_V_1_1 = "0000000000000000";
    shift_reg_V_1_0 = "0000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fir_filter_b_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, extLd4_loc_channel, "(port)extLd4_loc_channel");
    sc_trace(mVcdFile, y_V, "(port)y_V");
    sc_trace(mVcdFile, y_V_ap_vld, "(port)y_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, shift_reg_V_1_30, "shift_reg_V_1_30");
    sc_trace(mVcdFile, shift_reg_V_1_29, "shift_reg_V_1_29");
    sc_trace(mVcdFile, shift_reg_V_1_28, "shift_reg_V_1_28");
    sc_trace(mVcdFile, shift_reg_V_1_27, "shift_reg_V_1_27");
    sc_trace(mVcdFile, shift_reg_V_1_26, "shift_reg_V_1_26");
    sc_trace(mVcdFile, shift_reg_V_1_25, "shift_reg_V_1_25");
    sc_trace(mVcdFile, shift_reg_V_1_24, "shift_reg_V_1_24");
    sc_trace(mVcdFile, shift_reg_V_1_23, "shift_reg_V_1_23");
    sc_trace(mVcdFile, shift_reg_V_1_22, "shift_reg_V_1_22");
    sc_trace(mVcdFile, shift_reg_V_1_21, "shift_reg_V_1_21");
    sc_trace(mVcdFile, shift_reg_V_1_20, "shift_reg_V_1_20");
    sc_trace(mVcdFile, shift_reg_V_1_19, "shift_reg_V_1_19");
    sc_trace(mVcdFile, shift_reg_V_1_18, "shift_reg_V_1_18");
    sc_trace(mVcdFile, shift_reg_V_1_17, "shift_reg_V_1_17");
    sc_trace(mVcdFile, shift_reg_V_1_16, "shift_reg_V_1_16");
    sc_trace(mVcdFile, shift_reg_V_1_15, "shift_reg_V_1_15");
    sc_trace(mVcdFile, shift_reg_V_1_14, "shift_reg_V_1_14");
    sc_trace(mVcdFile, shift_reg_V_1_13, "shift_reg_V_1_13");
    sc_trace(mVcdFile, shift_reg_V_1_12, "shift_reg_V_1_12");
    sc_trace(mVcdFile, shift_reg_V_1_11, "shift_reg_V_1_11");
    sc_trace(mVcdFile, shift_reg_V_1_10, "shift_reg_V_1_10");
    sc_trace(mVcdFile, shift_reg_V_1_9, "shift_reg_V_1_9");
    sc_trace(mVcdFile, shift_reg_V_1_8, "shift_reg_V_1_8");
    sc_trace(mVcdFile, shift_reg_V_1_7, "shift_reg_V_1_7");
    sc_trace(mVcdFile, shift_reg_V_1_6, "shift_reg_V_1_6");
    sc_trace(mVcdFile, shift_reg_V_1_5, "shift_reg_V_1_5");
    sc_trace(mVcdFile, shift_reg_V_1_4, "shift_reg_V_1_4");
    sc_trace(mVcdFile, shift_reg_V_1_3, "shift_reg_V_1_3");
    sc_trace(mVcdFile, shift_reg_V_1_2, "shift_reg_V_1_2");
    sc_trace(mVcdFile, shift_reg_V_1_1, "shift_reg_V_1_1");
    sc_trace(mVcdFile, shift_reg_V_1_0, "shift_reg_V_1_0");
    sc_trace(mVcdFile, mul_ln700_fu_133_p2, "mul_ln700_fu_133_p2");
    sc_trace(mVcdFile, mul_ln700_reg_784, "mul_ln700_reg_784");
    sc_trace(mVcdFile, mul_ln700_1_fu_149_p2, "mul_ln700_1_fu_149_p2");
    sc_trace(mVcdFile, mul_ln700_1_reg_789, "mul_ln700_1_reg_789");
    sc_trace(mVcdFile, mul_ln700_2_fu_165_p2, "mul_ln700_2_fu_165_p2");
    sc_trace(mVcdFile, mul_ln700_2_reg_794, "mul_ln700_2_reg_794");
    sc_trace(mVcdFile, mul_ln700_3_fu_181_p2, "mul_ln700_3_fu_181_p2");
    sc_trace(mVcdFile, mul_ln700_3_reg_799, "mul_ln700_3_reg_799");
    sc_trace(mVcdFile, mul_ln700_4_fu_197_p2, "mul_ln700_4_fu_197_p2");
    sc_trace(mVcdFile, mul_ln700_4_reg_804, "mul_ln700_4_reg_804");
    sc_trace(mVcdFile, mul_ln700_5_fu_213_p2, "mul_ln700_5_fu_213_p2");
    sc_trace(mVcdFile, mul_ln700_5_reg_809, "mul_ln700_5_reg_809");
    sc_trace(mVcdFile, mul_ln700_6_fu_229_p2, "mul_ln700_6_fu_229_p2");
    sc_trace(mVcdFile, mul_ln700_6_reg_814, "mul_ln700_6_reg_814");
    sc_trace(mVcdFile, mul_ln700_7_fu_245_p2, "mul_ln700_7_fu_245_p2");
    sc_trace(mVcdFile, mul_ln700_7_reg_819, "mul_ln700_7_reg_819");
    sc_trace(mVcdFile, mul_ln700_8_fu_261_p2, "mul_ln700_8_fu_261_p2");
    sc_trace(mVcdFile, mul_ln700_8_reg_824, "mul_ln700_8_reg_824");
    sc_trace(mVcdFile, mul_ln700_9_fu_277_p2, "mul_ln700_9_fu_277_p2");
    sc_trace(mVcdFile, mul_ln700_9_reg_829, "mul_ln700_9_reg_829");
    sc_trace(mVcdFile, mul_ln700_10_fu_293_p2, "mul_ln700_10_fu_293_p2");
    sc_trace(mVcdFile, mul_ln700_10_reg_834, "mul_ln700_10_reg_834");
    sc_trace(mVcdFile, mul_ln700_11_fu_309_p2, "mul_ln700_11_fu_309_p2");
    sc_trace(mVcdFile, mul_ln700_11_reg_839, "mul_ln700_11_reg_839");
    sc_trace(mVcdFile, mul_ln700_12_fu_325_p2, "mul_ln700_12_fu_325_p2");
    sc_trace(mVcdFile, mul_ln700_12_reg_844, "mul_ln700_12_reg_844");
    sc_trace(mVcdFile, mul_ln700_13_fu_341_p2, "mul_ln700_13_fu_341_p2");
    sc_trace(mVcdFile, mul_ln700_13_reg_849, "mul_ln700_13_reg_849");
    sc_trace(mVcdFile, mul_ln700_14_fu_357_p2, "mul_ln700_14_fu_357_p2");
    sc_trace(mVcdFile, mul_ln700_14_reg_854, "mul_ln700_14_reg_854");
    sc_trace(mVcdFile, mul_ln700_15_fu_373_p2, "mul_ln700_15_fu_373_p2");
    sc_trace(mVcdFile, mul_ln700_15_reg_859, "mul_ln700_15_reg_859");
    sc_trace(mVcdFile, mul_ln700_16_fu_389_p2, "mul_ln700_16_fu_389_p2");
    sc_trace(mVcdFile, mul_ln700_16_reg_864, "mul_ln700_16_reg_864");
    sc_trace(mVcdFile, mul_ln700_17_fu_405_p2, "mul_ln700_17_fu_405_p2");
    sc_trace(mVcdFile, mul_ln700_17_reg_869, "mul_ln700_17_reg_869");
    sc_trace(mVcdFile, mul_ln700_18_fu_421_p2, "mul_ln700_18_fu_421_p2");
    sc_trace(mVcdFile, mul_ln700_18_reg_874, "mul_ln700_18_reg_874");
    sc_trace(mVcdFile, mul_ln700_19_fu_437_p2, "mul_ln700_19_fu_437_p2");
    sc_trace(mVcdFile, mul_ln700_19_reg_879, "mul_ln700_19_reg_879");
    sc_trace(mVcdFile, mul_ln700_20_fu_453_p2, "mul_ln700_20_fu_453_p2");
    sc_trace(mVcdFile, mul_ln700_20_reg_884, "mul_ln700_20_reg_884");
    sc_trace(mVcdFile, mul_ln700_21_fu_469_p2, "mul_ln700_21_fu_469_p2");
    sc_trace(mVcdFile, mul_ln700_21_reg_889, "mul_ln700_21_reg_889");
    sc_trace(mVcdFile, mul_ln700_22_fu_485_p2, "mul_ln700_22_fu_485_p2");
    sc_trace(mVcdFile, mul_ln700_22_reg_894, "mul_ln700_22_reg_894");
    sc_trace(mVcdFile, mul_ln700_23_fu_501_p2, "mul_ln700_23_fu_501_p2");
    sc_trace(mVcdFile, mul_ln700_23_reg_899, "mul_ln700_23_reg_899");
    sc_trace(mVcdFile, mul_ln700_24_fu_517_p2, "mul_ln700_24_fu_517_p2");
    sc_trace(mVcdFile, mul_ln700_24_reg_904, "mul_ln700_24_reg_904");
    sc_trace(mVcdFile, mul_ln700_25_fu_533_p2, "mul_ln700_25_fu_533_p2");
    sc_trace(mVcdFile, mul_ln700_25_reg_909, "mul_ln700_25_reg_909");
    sc_trace(mVcdFile, mul_ln700_26_fu_549_p2, "mul_ln700_26_fu_549_p2");
    sc_trace(mVcdFile, mul_ln700_26_reg_914, "mul_ln700_26_reg_914");
    sc_trace(mVcdFile, mul_ln700_27_fu_565_p2, "mul_ln700_27_fu_565_p2");
    sc_trace(mVcdFile, mul_ln700_27_reg_919, "mul_ln700_27_reg_919");
    sc_trace(mVcdFile, mul_ln700_28_fu_581_p2, "mul_ln700_28_fu_581_p2");
    sc_trace(mVcdFile, mul_ln700_28_reg_924, "mul_ln700_28_reg_924");
    sc_trace(mVcdFile, sext_ln180_fu_591_p1, "sext_ln180_fu_591_p1");
    sc_trace(mVcdFile, sext_ln180_reg_929, "sext_ln180_reg_929");
    sc_trace(mVcdFile, shift_reg_V_1_0_load_reg_934, "shift_reg_V_1_0_load_reg_934");
    sc_trace(mVcdFile, mul_ln700_31_fu_765_p2, "mul_ln700_31_fu_765_p2");
    sc_trace(mVcdFile, mul_ln700_31_reg_939, "mul_ln700_31_reg_939");
    sc_trace(mVcdFile, add_ln700_2_fu_632_p2, "add_ln700_2_fu_632_p2");
    sc_trace(mVcdFile, add_ln700_2_reg_944, "add_ln700_2_reg_944");
    sc_trace(mVcdFile, add_ln700_3_fu_638_p2, "add_ln700_3_fu_638_p2");
    sc_trace(mVcdFile, add_ln700_3_reg_949, "add_ln700_3_reg_949");
    sc_trace(mVcdFile, add_ln700_4_fu_642_p2, "add_ln700_4_fu_642_p2");
    sc_trace(mVcdFile, add_ln700_4_reg_954, "add_ln700_4_reg_954");
    sc_trace(mVcdFile, add_ln700_9_fu_654_p2, "add_ln700_9_fu_654_p2");
    sc_trace(mVcdFile, add_ln700_9_reg_959, "add_ln700_9_reg_959");
    sc_trace(mVcdFile, add_ln700_12_fu_668_p2, "add_ln700_12_fu_668_p2");
    sc_trace(mVcdFile, add_ln700_12_reg_964, "add_ln700_12_reg_964");
    sc_trace(mVcdFile, add_ln700_17_fu_682_p2, "add_ln700_17_fu_682_p2");
    sc_trace(mVcdFile, add_ln700_17_reg_969, "add_ln700_17_reg_969");
    sc_trace(mVcdFile, add_ln700_18_fu_688_p2, "add_ln700_18_fu_688_p2");
    sc_trace(mVcdFile, add_ln700_18_reg_974, "add_ln700_18_reg_974");
    sc_trace(mVcdFile, add_ln700_19_fu_692_p2, "add_ln700_19_fu_692_p2");
    sc_trace(mVcdFile, add_ln700_19_reg_979, "add_ln700_19_reg_979");
    sc_trace(mVcdFile, add_ln700_24_fu_704_p2, "add_ln700_24_fu_704_p2");
    sc_trace(mVcdFile, add_ln700_24_reg_984, "add_ln700_24_reg_984");
    sc_trace(mVcdFile, add_ln700_25_fu_710_p2, "add_ln700_25_fu_710_p2");
    sc_trace(mVcdFile, add_ln700_25_reg_989, "add_ln700_25_reg_989");
    sc_trace(mVcdFile, grp_fu_777_p3, "grp_fu_777_p3");
    sc_trace(mVcdFile, add_ln700_26_reg_994, "add_ln700_26_reg_994");
    sc_trace(mVcdFile, add_ln700_14_fu_727_p2, "add_ln700_14_fu_727_p2");
    sc_trace(mVcdFile, add_ln700_14_reg_999, "add_ln700_14_reg_999");
    sc_trace(mVcdFile, add_ln700_21_fu_737_p2, "add_ln700_21_fu_737_p2");
    sc_trace(mVcdFile, add_ln700_21_reg_1004, "add_ln700_21_reg_1004");
    sc_trace(mVcdFile, add_ln700_28_fu_750_p2, "add_ln700_28_fu_750_p2");
    sc_trace(mVcdFile, add_ln700_28_reg_1009, "add_ln700_28_reg_1009");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, mul_ln700_fu_133_p0, "mul_ln700_fu_133_p0");
    sc_trace(mVcdFile, mul_ln700_1_fu_149_p0, "mul_ln700_1_fu_149_p0");
    sc_trace(mVcdFile, mul_ln700_2_fu_165_p0, "mul_ln700_2_fu_165_p0");
    sc_trace(mVcdFile, mul_ln700_3_fu_181_p0, "mul_ln700_3_fu_181_p0");
    sc_trace(mVcdFile, mul_ln700_4_fu_197_p0, "mul_ln700_4_fu_197_p0");
    sc_trace(mVcdFile, mul_ln700_5_fu_213_p0, "mul_ln700_5_fu_213_p0");
    sc_trace(mVcdFile, mul_ln700_6_fu_229_p0, "mul_ln700_6_fu_229_p0");
    sc_trace(mVcdFile, mul_ln700_7_fu_245_p0, "mul_ln700_7_fu_245_p0");
    sc_trace(mVcdFile, mul_ln700_8_fu_261_p0, "mul_ln700_8_fu_261_p0");
    sc_trace(mVcdFile, mul_ln700_9_fu_277_p0, "mul_ln700_9_fu_277_p0");
    sc_trace(mVcdFile, mul_ln700_10_fu_293_p0, "mul_ln700_10_fu_293_p0");
    sc_trace(mVcdFile, mul_ln700_11_fu_309_p0, "mul_ln700_11_fu_309_p0");
    sc_trace(mVcdFile, mul_ln700_12_fu_325_p0, "mul_ln700_12_fu_325_p0");
    sc_trace(mVcdFile, mul_ln700_13_fu_341_p0, "mul_ln700_13_fu_341_p0");
    sc_trace(mVcdFile, mul_ln700_14_fu_357_p0, "mul_ln700_14_fu_357_p0");
    sc_trace(mVcdFile, mul_ln700_15_fu_373_p0, "mul_ln700_15_fu_373_p0");
    sc_trace(mVcdFile, mul_ln700_16_fu_389_p0, "mul_ln700_16_fu_389_p0");
    sc_trace(mVcdFile, mul_ln700_17_fu_405_p0, "mul_ln700_17_fu_405_p0");
    sc_trace(mVcdFile, mul_ln700_18_fu_421_p0, "mul_ln700_18_fu_421_p0");
    sc_trace(mVcdFile, mul_ln700_19_fu_437_p0, "mul_ln700_19_fu_437_p0");
    sc_trace(mVcdFile, mul_ln700_20_fu_453_p0, "mul_ln700_20_fu_453_p0");
    sc_trace(mVcdFile, mul_ln700_21_fu_469_p0, "mul_ln700_21_fu_469_p0");
    sc_trace(mVcdFile, mul_ln700_22_fu_485_p0, "mul_ln700_22_fu_485_p0");
    sc_trace(mVcdFile, mul_ln700_23_fu_501_p0, "mul_ln700_23_fu_501_p0");
    sc_trace(mVcdFile, mul_ln700_24_fu_517_p0, "mul_ln700_24_fu_517_p0");
    sc_trace(mVcdFile, mul_ln700_25_fu_533_p0, "mul_ln700_25_fu_533_p0");
    sc_trace(mVcdFile, mul_ln700_26_fu_549_p0, "mul_ln700_26_fu_549_p0");
    sc_trace(mVcdFile, mul_ln700_27_fu_565_p0, "mul_ln700_27_fu_565_p0");
    sc_trace(mVcdFile, mul_ln700_28_fu_581_p0, "mul_ln700_28_fu_581_p0");
    sc_trace(mVcdFile, sext_ln180_fu_591_p0, "sext_ln180_fu_591_p0");
    sc_trace(mVcdFile, add_ln700_fu_624_p2, "add_ln700_fu_624_p2");
    sc_trace(mVcdFile, add_ln700_1_fu_628_p2, "add_ln700_1_fu_628_p2");
    sc_trace(mVcdFile, add_ln700_7_fu_646_p2, "add_ln700_7_fu_646_p2");
    sc_trace(mVcdFile, add_ln700_8_fu_650_p2, "add_ln700_8_fu_650_p2");
    sc_trace(mVcdFile, add_ln700_10_fu_660_p2, "add_ln700_10_fu_660_p2");
    sc_trace(mVcdFile, add_ln700_11_fu_664_p2, "add_ln700_11_fu_664_p2");
    sc_trace(mVcdFile, add_ln700_15_fu_674_p2, "add_ln700_15_fu_674_p2");
    sc_trace(mVcdFile, add_ln700_16_fu_678_p2, "add_ln700_16_fu_678_p2");
    sc_trace(mVcdFile, add_ln700_22_fu_696_p2, "add_ln700_22_fu_696_p2");
    sc_trace(mVcdFile, add_ln700_23_fu_700_p2, "add_ln700_23_fu_700_p2");
    sc_trace(mVcdFile, mul_ln700_29_fu_771_p2, "mul_ln700_29_fu_771_p2");
    sc_trace(mVcdFile, add_ln700_5_fu_714_p2, "add_ln700_5_fu_714_p2");
    sc_trace(mVcdFile, add_ln700_6_fu_718_p2, "add_ln700_6_fu_718_p2");
    sc_trace(mVcdFile, add_ln700_13_fu_723_p2, "add_ln700_13_fu_723_p2");
    sc_trace(mVcdFile, add_ln700_20_fu_733_p2, "add_ln700_20_fu_733_p2");
    sc_trace(mVcdFile, sext_ln700_1_fu_742_p1, "sext_ln700_1_fu_742_p1");
    sc_trace(mVcdFile, add_ln700_27_fu_745_p2, "add_ln700_27_fu_745_p2");
    sc_trace(mVcdFile, add_ln700_29_fu_755_p2, "add_ln700_29_fu_755_p2");
    sc_trace(mVcdFile, mul_ln700_31_fu_765_p1, "mul_ln700_31_fu_765_p1");
    sc_trace(mVcdFile, mul_ln700_29_fu_771_p0, "mul_ln700_29_fu_771_p0");
    sc_trace(mVcdFile, mul_ln700_29_fu_771_p1, "mul_ln700_29_fu_771_p1");
    sc_trace(mVcdFile, grp_fu_777_p1, "grp_fu_777_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to2, "ap_idle_pp0_0to2");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

fir_filter_b::~fir_filter_b() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete d_conv_mul_mul_16bkb_U14;
    delete d_conv_mul_mul_16cud_U15;
    delete d_conv_mac_muladddEe_U16;
}

void fir_filter_b::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        add_ln700_12_reg_964 = add_ln700_12_fu_668_p2.read();
        add_ln700_17_reg_969 = add_ln700_17_fu_682_p2.read();
        add_ln700_18_reg_974 = add_ln700_18_fu_688_p2.read();
        add_ln700_19_reg_979 = add_ln700_19_fu_692_p2.read();
        add_ln700_24_reg_984 = add_ln700_24_fu_704_p2.read();
        add_ln700_25_reg_989 = add_ln700_25_fu_710_p2.read();
        add_ln700_2_reg_944 = add_ln700_2_fu_632_p2.read();
        add_ln700_3_reg_949 = add_ln700_3_fu_638_p2.read();
        add_ln700_4_reg_954 = add_ln700_4_fu_642_p2.read();
        add_ln700_9_reg_959 = add_ln700_9_fu_654_p2.read();
        mul_ln700_10_reg_834 = mul_ln700_10_fu_293_p2.read();
        mul_ln700_11_reg_839 = mul_ln700_11_fu_309_p2.read();
        mul_ln700_12_reg_844 = mul_ln700_12_fu_325_p2.read();
        mul_ln700_13_reg_849 = mul_ln700_13_fu_341_p2.read();
        mul_ln700_14_reg_854 = mul_ln700_14_fu_357_p2.read();
        mul_ln700_15_reg_859 = mul_ln700_15_fu_373_p2.read();
        mul_ln700_16_reg_864 = mul_ln700_16_fu_389_p2.read();
        mul_ln700_17_reg_869 = mul_ln700_17_fu_405_p2.read();
        mul_ln700_18_reg_874 = mul_ln700_18_fu_421_p2.read();
        mul_ln700_19_reg_879 = mul_ln700_19_fu_437_p2.read();
        mul_ln700_1_reg_789 = mul_ln700_1_fu_149_p2.read();
        mul_ln700_20_reg_884 = mul_ln700_20_fu_453_p2.read();
        mul_ln700_21_reg_889 = mul_ln700_21_fu_469_p2.read();
        mul_ln700_22_reg_894 = mul_ln700_22_fu_485_p2.read();
        mul_ln700_23_reg_899 = mul_ln700_23_fu_501_p2.read();
        mul_ln700_24_reg_904 = mul_ln700_24_fu_517_p2.read();
        mul_ln700_25_reg_909 = mul_ln700_25_fu_533_p2.read();
        mul_ln700_26_reg_914 = mul_ln700_26_fu_549_p2.read();
        mul_ln700_27_reg_919 = mul_ln700_27_fu_565_p2.read();
        mul_ln700_28_reg_924 = mul_ln700_28_fu_581_p2.read();
        mul_ln700_2_reg_794 = mul_ln700_2_fu_165_p2.read();
        mul_ln700_31_reg_939 = mul_ln700_31_fu_765_p2.read();
        mul_ln700_3_reg_799 = mul_ln700_3_fu_181_p2.read();
        mul_ln700_4_reg_804 = mul_ln700_4_fu_197_p2.read();
        mul_ln700_5_reg_809 = mul_ln700_5_fu_213_p2.read();
        mul_ln700_6_reg_814 = mul_ln700_6_fu_229_p2.read();
        mul_ln700_7_reg_819 = mul_ln700_7_fu_245_p2.read();
        mul_ln700_8_reg_824 = mul_ln700_8_fu_261_p2.read();
        mul_ln700_9_reg_829 = mul_ln700_9_fu_277_p2.read();
        mul_ln700_reg_784 = mul_ln700_fu_133_p2.read();
        sext_ln180_reg_929 = sext_ln180_fu_591_p1.read();
        shift_reg_V_1_0_load_reg_934 = shift_reg_V_1_0.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        add_ln700_14_reg_999 = add_ln700_14_fu_727_p2.read();
        add_ln700_21_reg_1004 = add_ln700_21_fu_737_p2.read();
        add_ln700_28_reg_1009 = add_ln700_28_fu_750_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        add_ln700_26_reg_994 = grp_fu_777_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        shift_reg_V_1_0 = extLd4_loc_channel.read();
        shift_reg_V_1_1 = shift_reg_V_1_0.read();
        shift_reg_V_1_10 = shift_reg_V_1_9.read();
        shift_reg_V_1_11 = shift_reg_V_1_10.read();
        shift_reg_V_1_12 = shift_reg_V_1_11.read();
        shift_reg_V_1_13 = shift_reg_V_1_12.read();
        shift_reg_V_1_14 = shift_reg_V_1_13.read();
        shift_reg_V_1_15 = shift_reg_V_1_14.read();
        shift_reg_V_1_16 = shift_reg_V_1_15.read();
        shift_reg_V_1_17 = shift_reg_V_1_16.read();
        shift_reg_V_1_18 = shift_reg_V_1_17.read();
        shift_reg_V_1_19 = shift_reg_V_1_18.read();
        shift_reg_V_1_2 = sext_ln180_fu_591_p1.read();
        shift_reg_V_1_20 = shift_reg_V_1_19.read();
        shift_reg_V_1_21 = shift_reg_V_1_20.read();
        shift_reg_V_1_22 = shift_reg_V_1_21.read();
        shift_reg_V_1_23 = shift_reg_V_1_22.read();
        shift_reg_V_1_24 = shift_reg_V_1_23.read();
        shift_reg_V_1_25 = shift_reg_V_1_24.read();
        shift_reg_V_1_26 = shift_reg_V_1_25.read();
        shift_reg_V_1_27 = shift_reg_V_1_26.read();
        shift_reg_V_1_28 = shift_reg_V_1_27.read();
        shift_reg_V_1_29 = shift_reg_V_1_28.read();
        shift_reg_V_1_3 = shift_reg_V_1_2.read();
        shift_reg_V_1_30 = shift_reg_V_1_29.read();
        shift_reg_V_1_4 = shift_reg_V_1_3.read();
        shift_reg_V_1_5 = shift_reg_V_1_4.read();
        shift_reg_V_1_6 = shift_reg_V_1_5.read();
        shift_reg_V_1_7 = shift_reg_V_1_6.read();
        shift_reg_V_1_8 = shift_reg_V_1_7.read();
        shift_reg_V_1_9 = shift_reg_V_1_8.read();
    }
}

void fir_filter_b::thread_add_ln700_10_fu_660_p2() {
    add_ln700_10_fu_660_p2 = (!mul_ln700_13_reg_849.read().is_01() || !mul_ln700_12_reg_844.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_13_reg_849.read()) + sc_biguint<32>(mul_ln700_12_reg_844.read()));
}

void fir_filter_b::thread_add_ln700_11_fu_664_p2() {
    add_ln700_11_fu_664_p2 = (!mul_ln700_15_reg_859.read().is_01() || !mul_ln700_14_reg_854.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_15_reg_859.read()) + sc_biguint<32>(mul_ln700_14_reg_854.read()));
}

void fir_filter_b::thread_add_ln700_12_fu_668_p2() {
    add_ln700_12_fu_668_p2 = (!add_ln700_10_fu_660_p2.read().is_01() || !add_ln700_11_fu_664_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_10_fu_660_p2.read()) + sc_biguint<32>(add_ln700_11_fu_664_p2.read()));
}

void fir_filter_b::thread_add_ln700_13_fu_723_p2() {
    add_ln700_13_fu_723_p2 = (!add_ln700_9_reg_959.read().is_01() || !add_ln700_12_reg_964.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_9_reg_959.read()) + sc_biguint<32>(add_ln700_12_reg_964.read()));
}

void fir_filter_b::thread_add_ln700_14_fu_727_p2() {
    add_ln700_14_fu_727_p2 = (!add_ln700_6_fu_718_p2.read().is_01() || !add_ln700_13_fu_723_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_6_fu_718_p2.read()) + sc_biguint<32>(add_ln700_13_fu_723_p2.read()));
}

void fir_filter_b::thread_add_ln700_15_fu_674_p2() {
    add_ln700_15_fu_674_p2 = (!mul_ln700_17_reg_869.read().is_01() || !mul_ln700_16_reg_864.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_17_reg_869.read()) + sc_biguint<32>(mul_ln700_16_reg_864.read()));
}

void fir_filter_b::thread_add_ln700_16_fu_678_p2() {
    add_ln700_16_fu_678_p2 = (!mul_ln700_19_reg_879.read().is_01() || !mul_ln700_18_reg_874.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_19_reg_879.read()) + sc_biguint<32>(mul_ln700_18_reg_874.read()));
}

void fir_filter_b::thread_add_ln700_17_fu_682_p2() {
    add_ln700_17_fu_682_p2 = (!add_ln700_15_fu_674_p2.read().is_01() || !add_ln700_16_fu_678_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_15_fu_674_p2.read()) + sc_biguint<32>(add_ln700_16_fu_678_p2.read()));
}

void fir_filter_b::thread_add_ln700_18_fu_688_p2() {
    add_ln700_18_fu_688_p2 = (!mul_ln700_21_reg_889.read().is_01() || !mul_ln700_20_reg_884.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_21_reg_889.read()) + sc_biguint<32>(mul_ln700_20_reg_884.read()));
}

void fir_filter_b::thread_add_ln700_19_fu_692_p2() {
    add_ln700_19_fu_692_p2 = (!mul_ln700_23_reg_899.read().is_01() || !mul_ln700_22_reg_894.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_23_reg_899.read()) + sc_biguint<32>(mul_ln700_22_reg_894.read()));
}

void fir_filter_b::thread_add_ln700_1_fu_628_p2() {
    add_ln700_1_fu_628_p2 = (!mul_ln700_3_reg_799.read().is_01() || !mul_ln700_2_reg_794.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_3_reg_799.read()) + sc_biguint<32>(mul_ln700_2_reg_794.read()));
}

void fir_filter_b::thread_add_ln700_20_fu_733_p2() {
    add_ln700_20_fu_733_p2 = (!add_ln700_18_reg_974.read().is_01() || !add_ln700_19_reg_979.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_18_reg_974.read()) + sc_biguint<32>(add_ln700_19_reg_979.read()));
}

void fir_filter_b::thread_add_ln700_21_fu_737_p2() {
    add_ln700_21_fu_737_p2 = (!add_ln700_17_reg_969.read().is_01() || !add_ln700_20_fu_733_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_17_reg_969.read()) + sc_biguint<32>(add_ln700_20_fu_733_p2.read()));
}

void fir_filter_b::thread_add_ln700_22_fu_696_p2() {
    add_ln700_22_fu_696_p2 = (!mul_ln700_25_reg_909.read().is_01() || !mul_ln700_24_reg_904.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_25_reg_909.read()) + sc_biguint<32>(mul_ln700_24_reg_904.read()));
}

void fir_filter_b::thread_add_ln700_23_fu_700_p2() {
    add_ln700_23_fu_700_p2 = (!mul_ln700_27_reg_919.read().is_01() || !mul_ln700_26_reg_914.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_27_reg_919.read()) + sc_biguint<32>(mul_ln700_26_reg_914.read()));
}

void fir_filter_b::thread_add_ln700_24_fu_704_p2() {
    add_ln700_24_fu_704_p2 = (!add_ln700_22_fu_696_p2.read().is_01() || !add_ln700_23_fu_700_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_22_fu_696_p2.read()) + sc_biguint<32>(add_ln700_23_fu_700_p2.read()));
}

void fir_filter_b::thread_add_ln700_25_fu_710_p2() {
    add_ln700_25_fu_710_p2 = (!mul_ln700_29_fu_771_p2.read().is_01() || !mul_ln700_28_reg_924.read().is_01())? sc_lv<32>(): (sc_bigint<32>(mul_ln700_29_fu_771_p2.read()) + sc_biguint<32>(mul_ln700_28_reg_924.read()));
}

void fir_filter_b::thread_add_ln700_27_fu_745_p2() {
    add_ln700_27_fu_745_p2 = (!add_ln700_25_reg_989.read().is_01() || !sext_ln700_1_fu_742_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_25_reg_989.read()) + sc_bigint<32>(sext_ln700_1_fu_742_p1.read()));
}

void fir_filter_b::thread_add_ln700_28_fu_750_p2() {
    add_ln700_28_fu_750_p2 = (!add_ln700_24_reg_984.read().is_01() || !add_ln700_27_fu_745_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_24_reg_984.read()) + sc_biguint<32>(add_ln700_27_fu_745_p2.read()));
}

void fir_filter_b::thread_add_ln700_29_fu_755_p2() {
    add_ln700_29_fu_755_p2 = (!add_ln700_21_reg_1004.read().is_01() || !add_ln700_28_reg_1009.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_21_reg_1004.read()) + sc_biguint<32>(add_ln700_28_reg_1009.read()));
}

void fir_filter_b::thread_add_ln700_2_fu_632_p2() {
    add_ln700_2_fu_632_p2 = (!add_ln700_fu_624_p2.read().is_01() || !add_ln700_1_fu_628_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_fu_624_p2.read()) + sc_biguint<32>(add_ln700_1_fu_628_p2.read()));
}

void fir_filter_b::thread_add_ln700_3_fu_638_p2() {
    add_ln700_3_fu_638_p2 = (!mul_ln700_5_reg_809.read().is_01() || !mul_ln700_4_reg_804.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_5_reg_809.read()) + sc_biguint<32>(mul_ln700_4_reg_804.read()));
}

void fir_filter_b::thread_add_ln700_4_fu_642_p2() {
    add_ln700_4_fu_642_p2 = (!mul_ln700_7_reg_819.read().is_01() || !mul_ln700_6_reg_814.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_7_reg_819.read()) + sc_biguint<32>(mul_ln700_6_reg_814.read()));
}

void fir_filter_b::thread_add_ln700_5_fu_714_p2() {
    add_ln700_5_fu_714_p2 = (!add_ln700_3_reg_949.read().is_01() || !add_ln700_4_reg_954.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_3_reg_949.read()) + sc_biguint<32>(add_ln700_4_reg_954.read()));
}

void fir_filter_b::thread_add_ln700_6_fu_718_p2() {
    add_ln700_6_fu_718_p2 = (!add_ln700_2_reg_944.read().is_01() || !add_ln700_5_fu_714_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_2_reg_944.read()) + sc_biguint<32>(add_ln700_5_fu_714_p2.read()));
}

void fir_filter_b::thread_add_ln700_7_fu_646_p2() {
    add_ln700_7_fu_646_p2 = (!mul_ln700_9_reg_829.read().is_01() || !mul_ln700_8_reg_824.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_9_reg_829.read()) + sc_biguint<32>(mul_ln700_8_reg_824.read()));
}

void fir_filter_b::thread_add_ln700_8_fu_650_p2() {
    add_ln700_8_fu_650_p2 = (!mul_ln700_11_reg_839.read().is_01() || !mul_ln700_10_reg_834.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_11_reg_839.read()) + sc_biguint<32>(mul_ln700_10_reg_834.read()));
}

void fir_filter_b::thread_add_ln700_9_fu_654_p2() {
    add_ln700_9_fu_654_p2 = (!add_ln700_7_fu_646_p2.read().is_01() || !add_ln700_8_fu_650_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_7_fu_646_p2.read()) + sc_biguint<32>(add_ln700_8_fu_650_p2.read()));
}

void fir_filter_b::thread_add_ln700_fu_624_p2() {
    add_ln700_fu_624_p2 = (!mul_ln700_1_reg_789.read().is_01() || !mul_ln700_reg_784.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln700_1_reg_789.read()) + sc_biguint<32>(mul_ln700_reg_784.read()));
}

void fir_filter_b::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void fir_filter_b::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter_b::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void fir_filter_b::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void fir_filter_b::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void fir_filter_b::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void fir_filter_b::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter_b::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter_b::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter_b::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void fir_filter_b::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void fir_filter_b::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void fir_filter_b::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fir_filter_b::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void fir_filter_b::thread_ap_idle_pp0_0to2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0_0to2 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to2 = ap_const_logic_0;
    }
}

void fir_filter_b::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fir_filter_b::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to2.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void fir_filter_b::thread_grp_fu_777_p1() {
    grp_fu_777_p1 =  (sc_lv<10>) (ap_const_lv26_3FFFE5F);
}

void fir_filter_b::thread_mul_ln700_10_fu_293_p0() {
    mul_ln700_10_fu_293_p0 = shift_reg_V_1_20.read();
}

void fir_filter_b::thread_mul_ln700_10_fu_293_p2() {
    mul_ln700_10_fu_293_p2 = (!mul_ln700_10_fu_293_p0.read().is_01() || !ap_const_lv32_C83.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_10_fu_293_p0.read()) * sc_biguint<32>(ap_const_lv32_C83);
}

void fir_filter_b::thread_mul_ln700_11_fu_309_p0() {
    mul_ln700_11_fu_309_p0 = shift_reg_V_1_19.read();
}

void fir_filter_b::thread_mul_ln700_11_fu_309_p2() {
    mul_ln700_11_fu_309_p2 = (!mul_ln700_11_fu_309_p0.read().is_01() || !ap_const_lv32_104C.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_11_fu_309_p0.read()) * sc_biguint<32>(ap_const_lv32_104C);
}

void fir_filter_b::thread_mul_ln700_12_fu_325_p0() {
    mul_ln700_12_fu_325_p0 = shift_reg_V_1_18.read();
}

void fir_filter_b::thread_mul_ln700_12_fu_325_p2() {
    mul_ln700_12_fu_325_p2 = (!mul_ln700_12_fu_325_p0.read().is_01() || !ap_const_lv32_13D7.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_12_fu_325_p0.read()) * sc_biguint<32>(ap_const_lv32_13D7);
}

void fir_filter_b::thread_mul_ln700_13_fu_341_p0() {
    mul_ln700_13_fu_341_p0 = shift_reg_V_1_17.read();
}

void fir_filter_b::thread_mul_ln700_13_fu_341_p2() {
    mul_ln700_13_fu_341_p2 = (!mul_ln700_13_fu_341_p0.read().is_01() || !ap_const_lv32_16D5.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_13_fu_341_p0.read()) * sc_biguint<32>(ap_const_lv32_16D5);
}

void fir_filter_b::thread_mul_ln700_14_fu_357_p0() {
    mul_ln700_14_fu_357_p0 = shift_reg_V_1_16.read();
}

void fir_filter_b::thread_mul_ln700_14_fu_357_p2() {
    mul_ln700_14_fu_357_p2 = (!mul_ln700_14_fu_357_p0.read().is_01() || !ap_const_lv32_1901.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_14_fu_357_p0.read()) * sc_biguint<32>(ap_const_lv32_1901);
}

void fir_filter_b::thread_mul_ln700_15_fu_373_p0() {
    mul_ln700_15_fu_373_p0 = shift_reg_V_1_15.read();
}

void fir_filter_b::thread_mul_ln700_15_fu_373_p2() {
    mul_ln700_15_fu_373_p2 = (!mul_ln700_15_fu_373_p0.read().is_01() || !ap_const_lv32_1A25.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_15_fu_373_p0.read()) * sc_biguint<32>(ap_const_lv32_1A25);
}

void fir_filter_b::thread_mul_ln700_16_fu_389_p0() {
    mul_ln700_16_fu_389_p0 = shift_reg_V_1_14.read();
}

void fir_filter_b::thread_mul_ln700_16_fu_389_p2() {
    mul_ln700_16_fu_389_p2 = (!mul_ln700_16_fu_389_p0.read().is_01() || !ap_const_lv32_1A25.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_16_fu_389_p0.read()) * sc_biguint<32>(ap_const_lv32_1A25);
}

void fir_filter_b::thread_mul_ln700_17_fu_405_p0() {
    mul_ln700_17_fu_405_p0 = shift_reg_V_1_13.read();
}

void fir_filter_b::thread_mul_ln700_17_fu_405_p2() {
    mul_ln700_17_fu_405_p2 = (!mul_ln700_17_fu_405_p0.read().is_01() || !ap_const_lv32_1901.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_17_fu_405_p0.read()) * sc_biguint<32>(ap_const_lv32_1901);
}

void fir_filter_b::thread_mul_ln700_18_fu_421_p0() {
    mul_ln700_18_fu_421_p0 = shift_reg_V_1_12.read();
}

void fir_filter_b::thread_mul_ln700_18_fu_421_p2() {
    mul_ln700_18_fu_421_p2 = (!mul_ln700_18_fu_421_p0.read().is_01() || !ap_const_lv32_16D5.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_18_fu_421_p0.read()) * sc_biguint<32>(ap_const_lv32_16D5);
}

void fir_filter_b::thread_mul_ln700_19_fu_437_p0() {
    mul_ln700_19_fu_437_p0 = shift_reg_V_1_11.read();
}

void fir_filter_b::thread_mul_ln700_19_fu_437_p2() {
    mul_ln700_19_fu_437_p2 = (!mul_ln700_19_fu_437_p0.read().is_01() || !ap_const_lv32_13D7.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_19_fu_437_p0.read()) * sc_biguint<32>(ap_const_lv32_13D7);
}

void fir_filter_b::thread_mul_ln700_1_fu_149_p0() {
    mul_ln700_1_fu_149_p0 = shift_reg_V_1_29.read();
}

void fir_filter_b::thread_mul_ln700_1_fu_149_p2() {
    mul_ln700_1_fu_149_p2 = (!mul_ln700_1_fu_149_p0.read().is_01() || !ap_const_lv32_FFFFFE5F.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_1_fu_149_p0.read()) * sc_bigint<32>(ap_const_lv32_FFFFFE5F);
}

void fir_filter_b::thread_mul_ln700_20_fu_453_p0() {
    mul_ln700_20_fu_453_p0 = shift_reg_V_1_10.read();
}

void fir_filter_b::thread_mul_ln700_20_fu_453_p2() {
    mul_ln700_20_fu_453_p2 = (!mul_ln700_20_fu_453_p0.read().is_01() || !ap_const_lv32_104C.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_20_fu_453_p0.read()) * sc_biguint<32>(ap_const_lv32_104C);
}

void fir_filter_b::thread_mul_ln700_21_fu_469_p0() {
    mul_ln700_21_fu_469_p0 = shift_reg_V_1_9.read();
}

void fir_filter_b::thread_mul_ln700_21_fu_469_p2() {
    mul_ln700_21_fu_469_p2 = (!mul_ln700_21_fu_469_p0.read().is_01() || !ap_const_lv32_C83.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_21_fu_469_p0.read()) * sc_biguint<32>(ap_const_lv32_C83);
}

void fir_filter_b::thread_mul_ln700_22_fu_485_p0() {
    mul_ln700_22_fu_485_p0 = shift_reg_V_1_8.read();
}

void fir_filter_b::thread_mul_ln700_22_fu_485_p2() {
    mul_ln700_22_fu_485_p2 = (!mul_ln700_22_fu_485_p0.read().is_01() || !ap_const_lv32_8CC.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_22_fu_485_p0.read()) * sc_biguint<32>(ap_const_lv32_8CC);
}

void fir_filter_b::thread_mul_ln700_23_fu_501_p0() {
    mul_ln700_23_fu_501_p0 = shift_reg_V_1_7.read();
}

void fir_filter_b::thread_mul_ln700_23_fu_501_p2() {
    mul_ln700_23_fu_501_p2 = (!mul_ln700_23_fu_501_p0.read().is_01() || !ap_const_lv32_56A.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_23_fu_501_p0.read()) * sc_biguint<32>(ap_const_lv32_56A);
}

void fir_filter_b::thread_mul_ln700_24_fu_517_p0() {
    mul_ln700_24_fu_517_p0 = shift_reg_V_1_6.read();
}

void fir_filter_b::thread_mul_ln700_24_fu_517_p2() {
    mul_ln700_24_fu_517_p2 = (!mul_ln700_24_fu_517_p0.read().is_01() || !ap_const_lv32_294.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_24_fu_517_p0.read()) * sc_biguint<32>(ap_const_lv32_294);
}

void fir_filter_b::thread_mul_ln700_25_fu_533_p0() {
    mul_ln700_25_fu_533_p0 = shift_reg_V_1_5.read();
}

void fir_filter_b::thread_mul_ln700_25_fu_533_p2() {
    mul_ln700_25_fu_533_p2 = (!mul_ln700_25_fu_533_p0.read().is_01() || !ap_const_lv32_67.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_25_fu_533_p0.read()) * sc_biguint<32>(ap_const_lv32_67);
}

void fir_filter_b::thread_mul_ln700_26_fu_549_p0() {
    mul_ln700_26_fu_549_p0 = shift_reg_V_1_4.read();
}

void fir_filter_b::thread_mul_ln700_26_fu_549_p2() {
    mul_ln700_26_fu_549_p2 = (!mul_ln700_26_fu_549_p0.read().is_01() || !ap_const_lv32_FFFFFEED.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_26_fu_549_p0.read()) * sc_bigint<32>(ap_const_lv32_FFFFFEED);
}

void fir_filter_b::thread_mul_ln700_27_fu_565_p0() {
    mul_ln700_27_fu_565_p0 = shift_reg_V_1_3.read();
}

void fir_filter_b::thread_mul_ln700_27_fu_565_p2() {
    mul_ln700_27_fu_565_p2 = (!mul_ln700_27_fu_565_p0.read().is_01() || !ap_const_lv32_FFFFFE1B.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_27_fu_565_p0.read()) * sc_bigint<32>(ap_const_lv32_FFFFFE1B);
}

void fir_filter_b::thread_mul_ln700_28_fu_581_p0() {
    mul_ln700_28_fu_581_p0 = shift_reg_V_1_2.read();
}

void fir_filter_b::thread_mul_ln700_28_fu_581_p2() {
    mul_ln700_28_fu_581_p2 = (!mul_ln700_28_fu_581_p0.read().is_01() || !ap_const_lv32_FFFFFDD6.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_28_fu_581_p0.read()) * sc_bigint<32>(ap_const_lv32_FFFFFDD6);
}

void fir_filter_b::thread_mul_ln700_29_fu_771_p0() {
    mul_ln700_29_fu_771_p0 =  (sc_lv<16>) (sext_ln180_reg_929.read());
}

void fir_filter_b::thread_mul_ln700_29_fu_771_p1() {
    mul_ln700_29_fu_771_p1 =  (sc_lv<11>) (ap_const_lv32_FFFFFDF9);
}

void fir_filter_b::thread_mul_ln700_2_fu_165_p0() {
    mul_ln700_2_fu_165_p0 = shift_reg_V_1_28.read();
}

void fir_filter_b::thread_mul_ln700_2_fu_165_p2() {
    mul_ln700_2_fu_165_p2 = (!mul_ln700_2_fu_165_p0.read().is_01() || !ap_const_lv32_FFFFFDF9.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_2_fu_165_p0.read()) * sc_bigint<32>(ap_const_lv32_FFFFFDF9);
}

void fir_filter_b::thread_mul_ln700_31_fu_765_p1() {
    mul_ln700_31_fu_765_p1 =  (sc_lv<10>) (ap_const_lv26_3FFFE27);
}

void fir_filter_b::thread_mul_ln700_3_fu_181_p0() {
    mul_ln700_3_fu_181_p0 = shift_reg_V_1_27.read();
}

void fir_filter_b::thread_mul_ln700_3_fu_181_p2() {
    mul_ln700_3_fu_181_p2 = (!mul_ln700_3_fu_181_p0.read().is_01() || !ap_const_lv32_FFFFFDD6.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_3_fu_181_p0.read()) * sc_bigint<32>(ap_const_lv32_FFFFFDD6);
}

void fir_filter_b::thread_mul_ln700_4_fu_197_p0() {
    mul_ln700_4_fu_197_p0 = shift_reg_V_1_26.read();
}

void fir_filter_b::thread_mul_ln700_4_fu_197_p2() {
    mul_ln700_4_fu_197_p2 = (!mul_ln700_4_fu_197_p0.read().is_01() || !ap_const_lv32_FFFFFE1B.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_4_fu_197_p0.read()) * sc_bigint<32>(ap_const_lv32_FFFFFE1B);
}

void fir_filter_b::thread_mul_ln700_5_fu_213_p0() {
    mul_ln700_5_fu_213_p0 = shift_reg_V_1_25.read();
}

void fir_filter_b::thread_mul_ln700_5_fu_213_p2() {
    mul_ln700_5_fu_213_p2 = (!mul_ln700_5_fu_213_p0.read().is_01() || !ap_const_lv32_FFFFFEED.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_5_fu_213_p0.read()) * sc_bigint<32>(ap_const_lv32_FFFFFEED);
}

void fir_filter_b::thread_mul_ln700_6_fu_229_p0() {
    mul_ln700_6_fu_229_p0 = shift_reg_V_1_24.read();
}

void fir_filter_b::thread_mul_ln700_6_fu_229_p2() {
    mul_ln700_6_fu_229_p2 = (!mul_ln700_6_fu_229_p0.read().is_01() || !ap_const_lv32_67.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_6_fu_229_p0.read()) * sc_biguint<32>(ap_const_lv32_67);
}

void fir_filter_b::thread_mul_ln700_7_fu_245_p0() {
    mul_ln700_7_fu_245_p0 = shift_reg_V_1_23.read();
}

void fir_filter_b::thread_mul_ln700_7_fu_245_p2() {
    mul_ln700_7_fu_245_p2 = (!mul_ln700_7_fu_245_p0.read().is_01() || !ap_const_lv32_294.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_7_fu_245_p0.read()) * sc_biguint<32>(ap_const_lv32_294);
}

void fir_filter_b::thread_mul_ln700_8_fu_261_p0() {
    mul_ln700_8_fu_261_p0 = shift_reg_V_1_22.read();
}

void fir_filter_b::thread_mul_ln700_8_fu_261_p2() {
    mul_ln700_8_fu_261_p2 = (!mul_ln700_8_fu_261_p0.read().is_01() || !ap_const_lv32_56A.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_8_fu_261_p0.read()) * sc_biguint<32>(ap_const_lv32_56A);
}

void fir_filter_b::thread_mul_ln700_9_fu_277_p0() {
    mul_ln700_9_fu_277_p0 = shift_reg_V_1_21.read();
}

void fir_filter_b::thread_mul_ln700_9_fu_277_p2() {
    mul_ln700_9_fu_277_p2 = (!mul_ln700_9_fu_277_p0.read().is_01() || !ap_const_lv32_8CC.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_9_fu_277_p0.read()) * sc_biguint<32>(ap_const_lv32_8CC);
}

void fir_filter_b::thread_mul_ln700_fu_133_p0() {
    mul_ln700_fu_133_p0 = shift_reg_V_1_30.read();
}

void fir_filter_b::thread_mul_ln700_fu_133_p2() {
    mul_ln700_fu_133_p2 = (!mul_ln700_fu_133_p0.read().is_01() || !ap_const_lv32_FFFFFE27.is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln700_fu_133_p0.read()) * sc_bigint<32>(ap_const_lv32_FFFFFE27);
}

void fir_filter_b::thread_sext_ln180_fu_591_p0() {
    sext_ln180_fu_591_p0 = shift_reg_V_1_1.read();
}

void fir_filter_b::thread_sext_ln180_fu_591_p1() {
    sext_ln180_fu_591_p1 = esl_sext<32,16>(sext_ln180_fu_591_p0.read());
}

void fir_filter_b::thread_sext_ln700_1_fu_742_p1() {
    sext_ln700_1_fu_742_p1 = esl_sext<32,26>(add_ln700_26_reg_994.read());
}

void fir_filter_b::thread_y_V() {
    y_V = (!add_ln700_14_reg_999.read().is_01() || !add_ln700_29_fu_755_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln700_14_reg_999.read()) + sc_biguint<32>(add_ln700_29_fu_755_p2.read()));
}

void fir_filter_b::thread_y_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        y_V_ap_vld = ap_const_logic_1;
    } else {
        y_V_ap_vld = ap_const_logic_0;
    }
}

void fir_filter_b::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

