// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "iq_mult.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic iq_mult::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic iq_mult::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> iq_mult::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<32> iq_mult::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool iq_mult::ap_const_boolean_1 = true;
const bool iq_mult::ap_const_boolean_0 = false;
const sc_lv<8> iq_mult::ap_const_lv8_FF = "11111111";
const sc_lv<8> iq_mult::ap_const_lv8_0 = "00000000";

iq_mult::iq_mult(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ref_i_V_empty_n );
    sensitive << ( ref_q_V_empty_n );
    sensitive << ( i_tmp_empty_n );
    sensitive << ( q_tmp_empty_n );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ref_i_V_empty_n );
    sensitive << ( ref_q_V_empty_n );
    sensitive << ( i_tmp_empty_n );
    sensitive << ( q_tmp_empty_n );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ref_i_V_empty_n );
    sensitive << ( ref_q_V_empty_n );
    sensitive << ( i_tmp_empty_n );
    sensitive << ( q_tmp_empty_n );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ref_i_V_empty_n );
    sensitive << ( ref_q_V_empty_n );
    sensitive << ( i_tmp_empty_n );
    sensitive << ( q_tmp_empty_n );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_idle_pp0_0to1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to1 );

    SC_METHOD(thread_i_tmp_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_tmp_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_i_tmp_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_q_tmp_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( q_tmp_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_q_tmp_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ref_i_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ref_i_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ref_i_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ref_q_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ref_q_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ref_q_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_select_ln35_fu_121_p3);
    sensitive << ( q_tmp_read_reg_158_pp0_iter1_reg );

    SC_METHOD(thread_sext_ln35_fu_133_p1);
    sensitive << ( tmp_q_fu_128_p2 );

    SC_METHOD(thread_tmp_i_fu_116_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ref_i_V_read_reg_143 );

    SC_METHOD(thread_tmp_i_fu_116_p2);
    sensitive << ( i_tmp_read_reg_153 );
    sensitive << ( tmp_i_fu_116_p0 );

    SC_METHOD(thread_tmp_q_fu_128_p2);
    sensitive << ( ref_q_V_read_reg_148_pp0_iter1_reg );
    sensitive << ( select_ln35_fu_121_p3 );

    SC_METHOD(thread_y);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_i_reg_163 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( sext_ln35_fu_133_p1 );

    SC_METHOD(thread_y_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "iq_mult_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ref_i_V_dout, "(port)ref_i_V_dout");
    sc_trace(mVcdFile, ref_i_V_empty_n, "(port)ref_i_V_empty_n");
    sc_trace(mVcdFile, ref_i_V_read, "(port)ref_i_V_read");
    sc_trace(mVcdFile, ref_q_V_dout, "(port)ref_q_V_dout");
    sc_trace(mVcdFile, ref_q_V_empty_n, "(port)ref_q_V_empty_n");
    sc_trace(mVcdFile, ref_q_V_read, "(port)ref_q_V_read");
    sc_trace(mVcdFile, i_tmp_dout, "(port)i_tmp_dout");
    sc_trace(mVcdFile, i_tmp_empty_n, "(port)i_tmp_empty_n");
    sc_trace(mVcdFile, i_tmp_read, "(port)i_tmp_read");
    sc_trace(mVcdFile, q_tmp_dout, "(port)q_tmp_dout");
    sc_trace(mVcdFile, q_tmp_empty_n, "(port)q_tmp_empty_n");
    sc_trace(mVcdFile, q_tmp_read, "(port)q_tmp_read");
    sc_trace(mVcdFile, y, "(port)y");
    sc_trace(mVcdFile, y_ap_vld, "(port)y_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_tmp_blk_n, "i_tmp_blk_n");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, q_tmp_blk_n, "q_tmp_blk_n");
    sc_trace(mVcdFile, ref_i_V_blk_n, "ref_i_V_blk_n");
    sc_trace(mVcdFile, ref_q_V_blk_n, "ref_q_V_blk_n");
    sc_trace(mVcdFile, ref_i_V_read_reg_143, "ref_i_V_read_reg_143");
    sc_trace(mVcdFile, ref_q_V_read_reg_148, "ref_q_V_read_reg_148");
    sc_trace(mVcdFile, ref_q_V_read_reg_148_pp0_iter1_reg, "ref_q_V_read_reg_148_pp0_iter1_reg");
    sc_trace(mVcdFile, i_tmp_read_reg_153, "i_tmp_read_reg_153");
    sc_trace(mVcdFile, q_tmp_read_reg_158, "q_tmp_read_reg_158");
    sc_trace(mVcdFile, q_tmp_read_reg_158_pp0_iter1_reg, "q_tmp_read_reg_158_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_i_fu_116_p2, "tmp_i_fu_116_p2");
    sc_trace(mVcdFile, tmp_i_reg_163, "tmp_i_reg_163");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, tmp_i_fu_116_p0, "tmp_i_fu_116_p0");
    sc_trace(mVcdFile, select_ln35_fu_121_p3, "select_ln35_fu_121_p3");
    sc_trace(mVcdFile, tmp_q_fu_128_p2, "tmp_q_fu_128_p2");
    sc_trace(mVcdFile, sext_ln35_fu_133_p1, "sext_ln35_fu_133_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to1, "ap_idle_pp0_0to1");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

iq_mult::~iq_mult() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void iq_mult::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_tmp_read_reg_153 = i_tmp_dout.read();
        q_tmp_read_reg_158 = q_tmp_dout.read();
        q_tmp_read_reg_158_pp0_iter1_reg = q_tmp_read_reg_158.read();
        ref_i_V_read_reg_143 = ref_i_V_dout.read();
        ref_q_V_read_reg_148 = ref_q_V_dout.read();
        ref_q_V_read_reg_148_pp0_iter1_reg = ref_q_V_read_reg_148.read();
        tmp_i_reg_163 = tmp_i_fu_116_p2.read();
    }
}

void iq_mult::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void iq_mult::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void iq_mult::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, ref_i_V_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, ref_q_V_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, i_tmp_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, q_tmp_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void iq_mult::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, ref_i_V_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, ref_q_V_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, i_tmp_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, q_tmp_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void iq_mult::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, ref_i_V_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, ref_q_V_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, i_tmp_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, q_tmp_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void iq_mult::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ref_i_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ref_q_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, i_tmp_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, q_tmp_empty_n.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void iq_mult::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void iq_mult::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void iq_mult::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void iq_mult::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void iq_mult::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void iq_mult::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void iq_mult::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void iq_mult::thread_ap_idle_pp0_0to1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0_0to1 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to1 = ap_const_logic_0;
    }
}

void iq_mult::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void iq_mult::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to1.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void iq_mult::thread_i_tmp_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        i_tmp_blk_n = i_tmp_empty_n.read();
    } else {
        i_tmp_blk_n = ap_const_logic_1;
    }
}

void iq_mult::thread_i_tmp_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_tmp_read = ap_const_logic_1;
    } else {
        i_tmp_read = ap_const_logic_0;
    }
}

void iq_mult::thread_q_tmp_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        q_tmp_blk_n = q_tmp_empty_n.read();
    } else {
        q_tmp_blk_n = ap_const_logic_1;
    }
}

void iq_mult::thread_q_tmp_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        q_tmp_read = ap_const_logic_1;
    } else {
        q_tmp_read = ap_const_logic_0;
    }
}

void iq_mult::thread_ref_i_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ref_i_V_blk_n = ref_i_V_empty_n.read();
    } else {
        ref_i_V_blk_n = ap_const_logic_1;
    }
}

void iq_mult::thread_ref_i_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ref_i_V_read = ap_const_logic_1;
    } else {
        ref_i_V_read = ap_const_logic_0;
    }
}

void iq_mult::thread_ref_q_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ref_q_V_blk_n = ref_q_V_empty_n.read();
    } else {
        ref_q_V_blk_n = ap_const_logic_1;
    }
}

void iq_mult::thread_ref_q_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ref_q_V_read = ap_const_logic_1;
    } else {
        ref_q_V_read = ap_const_logic_0;
    }
}

void iq_mult::thread_select_ln35_fu_121_p3() {
    select_ln35_fu_121_p3 = (!q_tmp_read_reg_158_pp0_iter1_reg.read()[0].is_01())? sc_lv<8>(): ((q_tmp_read_reg_158_pp0_iter1_reg.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void iq_mult::thread_sext_ln35_fu_133_p1() {
    sext_ln35_fu_133_p1 = esl_sext<32,8>(tmp_q_fu_128_p2.read());
}

void iq_mult::thread_tmp_i_fu_116_p0() {
    tmp_i_fu_116_p0 = ref_i_V_read_reg_143.read();
}

void iq_mult::thread_tmp_i_fu_116_p2() {
    tmp_i_fu_116_p2 = (!tmp_i_fu_116_p0.read().is_01() || !i_tmp_read_reg_153.read().is_01())? sc_lv<32>(): sc_bigint<8>(tmp_i_fu_116_p0.read()) * sc_bigint<32>(i_tmp_read_reg_153.read());
}

void iq_mult::thread_tmp_q_fu_128_p2() {
    tmp_q_fu_128_p2 = (ref_q_V_read_reg_148_pp0_iter1_reg.read() & select_ln35_fu_121_p3.read());
}

void iq_mult::thread_y() {
    y = (!tmp_i_reg_163.read().is_01() || !sext_ln35_fu_133_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_i_reg_163.read()) + sc_bigint<32>(sext_ln35_fu_133_p1.read()));
}

void iq_mult::thread_y_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        y_ap_vld = ap_const_logic_1;
    } else {
        y_ap_vld = ap_const_logic_0;
    }
}

void iq_mult::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

