// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Block_proc14 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        x_i,
        x_i_ap_vld,
        x_q,
        x_q_ap_vld,
        ref_i_V,
        ref_i_V_ap_vld,
        ref_q_V,
        ref_q_V_ap_vld,
        q_tmp_out_din,
        q_tmp_out_full_n,
        q_tmp_out_write,
        x_i_out_din,
        x_i_out_full_n,
        x_i_out_write,
        x_q_out_din,
        x_q_out_full_n,
        x_q_out_write,
        ref_i_V_out_din,
        ref_i_V_out_full_n,
        ref_i_V_out_write,
        ref_q_V_out_din,
        ref_q_V_out_full_n,
        ref_q_V_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] x_i;
input   x_i_ap_vld;
input  [31:0] x_q;
input   x_q_ap_vld;
input  [7:0] ref_i_V;
input   ref_i_V_ap_vld;
input  [7:0] ref_q_V;
input   ref_q_V_ap_vld;
output  [0:0] q_tmp_out_din;
input   q_tmp_out_full_n;
output   q_tmp_out_write;
output  [31:0] x_i_out_din;
input   x_i_out_full_n;
output   x_i_out_write;
output  [31:0] x_q_out_din;
input   x_q_out_full_n;
output   x_q_out_write;
output  [7:0] ref_i_V_out_din;
input   ref_i_V_out_full_n;
output   ref_i_V_out_write;
output  [7:0] ref_q_V_out_din;
input   ref_q_V_out_full_n;
output   ref_q_V_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg q_tmp_out_write;
reg x_i_out_write;
reg x_q_out_write;
reg ref_i_V_out_write;
reg ref_q_V_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    x_i_blk_n;
reg    x_q_blk_n;
reg    ref_i_V_blk_n;
reg    ref_q_V_blk_n;
reg    q_tmp_out_blk_n;
reg    x_i_out_blk_n;
reg    x_q_out_blk_n;
reg    ref_i_V_out_blk_n;
reg    ref_q_V_out_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ref_q_V_out_full_n == 1'b0) | (ref_i_V_out_full_n == 1'b0) | (x_q_out_full_n == 1'b0) | (x_i_out_full_n == 1'b0) | (q_tmp_out_full_n == 1'b0) | (ref_q_V_ap_vld == 1'b0) | (ref_i_V_ap_vld == 1'b0) | (x_q_ap_vld == 1'b0) | (x_i_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ref_q_V_out_full_n == 1'b0) | (ref_i_V_out_full_n == 1'b0) | (x_q_out_full_n == 1'b0) | (x_i_out_full_n == 1'b0) | (q_tmp_out_full_n == 1'b0) | (ref_q_V_ap_vld == 1'b0) | (ref_i_V_ap_vld == 1'b0) | (x_q_ap_vld == 1'b0) | (x_i_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ref_q_V_out_full_n == 1'b0) | (ref_i_V_out_full_n == 1'b0) | (x_q_out_full_n == 1'b0) | (x_i_out_full_n == 1'b0) | (q_tmp_out_full_n == 1'b0) | (ref_q_V_ap_vld == 1'b0) | (ref_i_V_ap_vld == 1'b0) | (x_q_ap_vld == 1'b0) | (x_i_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        q_tmp_out_blk_n = q_tmp_out_full_n;
    end else begin
        q_tmp_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ref_q_V_out_full_n == 1'b0) | (ref_i_V_out_full_n == 1'b0) | (x_q_out_full_n == 1'b0) | (x_i_out_full_n == 1'b0) | (q_tmp_out_full_n == 1'b0) | (ref_q_V_ap_vld == 1'b0) | (ref_i_V_ap_vld == 1'b0) | (x_q_ap_vld == 1'b0) | (x_i_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        q_tmp_out_write = 1'b1;
    end else begin
        q_tmp_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ref_i_V_blk_n = ref_i_V_ap_vld;
    end else begin
        ref_i_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ref_i_V_out_blk_n = ref_i_V_out_full_n;
    end else begin
        ref_i_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ref_q_V_out_full_n == 1'b0) | (ref_i_V_out_full_n == 1'b0) | (x_q_out_full_n == 1'b0) | (x_i_out_full_n == 1'b0) | (q_tmp_out_full_n == 1'b0) | (ref_q_V_ap_vld == 1'b0) | (ref_i_V_ap_vld == 1'b0) | (x_q_ap_vld == 1'b0) | (x_i_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ref_i_V_out_write = 1'b1;
    end else begin
        ref_i_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ref_q_V_blk_n = ref_q_V_ap_vld;
    end else begin
        ref_q_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ref_q_V_out_blk_n = ref_q_V_out_full_n;
    end else begin
        ref_q_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ref_q_V_out_full_n == 1'b0) | (ref_i_V_out_full_n == 1'b0) | (x_q_out_full_n == 1'b0) | (x_i_out_full_n == 1'b0) | (q_tmp_out_full_n == 1'b0) | (ref_q_V_ap_vld == 1'b0) | (ref_i_V_ap_vld == 1'b0) | (x_q_ap_vld == 1'b0) | (x_i_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ref_q_V_out_write = 1'b1;
    end else begin
        ref_q_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        x_i_blk_n = x_i_ap_vld;
    end else begin
        x_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        x_i_out_blk_n = x_i_out_full_n;
    end else begin
        x_i_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ref_q_V_out_full_n == 1'b0) | (ref_i_V_out_full_n == 1'b0) | (x_q_out_full_n == 1'b0) | (x_i_out_full_n == 1'b0) | (q_tmp_out_full_n == 1'b0) | (ref_q_V_ap_vld == 1'b0) | (ref_i_V_ap_vld == 1'b0) | (x_q_ap_vld == 1'b0) | (x_i_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        x_i_out_write = 1'b1;
    end else begin
        x_i_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        x_q_blk_n = x_q_ap_vld;
    end else begin
        x_q_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        x_q_out_blk_n = x_q_out_full_n;
    end else begin
        x_q_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ref_q_V_out_full_n == 1'b0) | (ref_i_V_out_full_n == 1'b0) | (x_q_out_full_n == 1'b0) | (x_i_out_full_n == 1'b0) | (q_tmp_out_full_n == 1'b0) | (ref_q_V_ap_vld == 1'b0) | (ref_i_V_ap_vld == 1'b0) | (x_q_ap_vld == 1'b0) | (x_i_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        x_q_out_write = 1'b1;
    end else begin
        x_q_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ref_q_V_out_full_n == 1'b0) | (ref_i_V_out_full_n == 1'b0) | (x_q_out_full_n == 1'b0) | (x_i_out_full_n == 1'b0) | (q_tmp_out_full_n == 1'b0) | (ref_q_V_ap_vld == 1'b0) | (ref_i_V_ap_vld == 1'b0) | (x_q_ap_vld == 1'b0) | (x_i_ap_vld == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign q_tmp_out_din = 1'd0;

assign ref_i_V_out_din = ref_i_V;

assign ref_q_V_out_din = ref_q_V;

assign start_out = real_start;

assign x_i_out_din = x_i;

assign x_q_out_din = x_q;

endmodule //Block_proc14
