@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Nov 24 12:53:55 +0300 2020
REM SW Build 2615518 on Fri Aug  9 15:55:25 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim sys_tb_behav -key {Behavioral:sim_1:Functional:sys_tb} -tclbatch sys_tb.tcl -protoinst "protoinst_files/bd_080f.protoinst" -protoinst "protoinst_files/dds_sys.protoinst" -log simulate.log"
call xsim  sys_tb_behav -key {Behavioral:sim_1:Functional:sys_tb} -tclbatch sys_tb.tcl -protoinst "protoinst_files/bd_080f.protoinst" -protoinst "protoinst_files/dds_sys.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
