# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/work/radar_course/lesson_15/vivado/fmcomms1/fmcomms1.srcs/sources_1/bd/system/ip/system_axi_ad9643_0_0/system_axi_ad9643_0_0.xci
# IP: The module: 'system_axi_ad9643_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/radar_course/lesson_15/vivado/fmcomms1/fmcomms1.srcs/sources_1/bd/system/ip/common/ad_axi_ip_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9643_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/work/radar_course/lesson_15/vivado/fmcomms1/fmcomms1.srcs/sources_1/bd/system/ip/system_axi_ad9643_0_0/axi_ad9643_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9643_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/work/radar_course/lesson_15/vivado/fmcomms1/fmcomms1.srcs/sources_1/bd/system/ip/system_axi_ad9643_0_0/system_axi_ad9643_0_0.xci
# IP: The module: 'system_axi_ad9643_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/radar_course/lesson_15/vivado/fmcomms1/fmcomms1.srcs/sources_1/bd/system/ip/common/ad_axi_ip_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9643_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/work/radar_course/lesson_15/vivado/fmcomms1/fmcomms1.srcs/sources_1/bd/system/ip/system_axi_ad9643_0_0/axi_ad9643_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9643_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
