@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 29 01:06:21 +0300 2020
REM SW Build 2615518 on Fri Aug  9 15:55:25 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim axi_dma_0_exdes_tb_behav -key {Behavioral:sim_1:Functional:axi_dma_0_exdes_tb} -tclbatch axi_dma_0_exdes_tb.tcl -log simulate.log"
call xsim  axi_dma_0_exdes_tb_behav -key {Behavioral:sim_1:Functional:axi_dma_0_exdes_tb} -tclbatch axi_dma_0_exdes_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
