-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1.3
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity iq_mult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_V : IN STD_LOGIC_VECTOR (7 downto 0);
    x_V_ap_vld : IN STD_LOGIC;
    ref_i_V : IN STD_LOGIC_VECTOR (7 downto 0);
    ref_i_V_ap_vld : IN STD_LOGIC;
    ref_q_V : IN STD_LOGIC_VECTOR (7 downto 0);
    ref_q_V_ap_vld : IN STD_LOGIC;
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of iq_mult is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal x_V_blk_n : STD_LOGIC;
    signal ref_i_V_blk_n : STD_LOGIC;
    signal ref_q_V_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ret_V_fu_36_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_fu_36_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal lhs_V_fu_28_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_1_fu_46_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_1_fu_46_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_fu_36_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_1_fu_46_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (ref_q_V_ap_vld = ap_const_logic_0) or (ref_i_V_ap_vld = ap_const_logic_0) or (x_V_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv16_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ref_q_V_ap_vld = ap_const_logic_0) or (ref_i_V_ap_vld = ap_const_logic_0) or (x_V_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_0_preg <= ret_V_fu_36_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv16_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ref_q_V_ap_vld = ap_const_logic_0) or (ref_i_V_ap_vld = ap_const_logic_0) or (x_V_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_1_preg <= ret_V_1_fu_46_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, x_V_ap_vld, ref_i_V_ap_vld, ref_q_V_ap_vld)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, x_V_ap_vld, ref_i_V_ap_vld, ref_q_V_ap_vld)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ref_q_V_ap_vld = ap_const_logic_0) or (ref_i_V_ap_vld = ap_const_logic_0) or (x_V_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, x_V_ap_vld, ref_i_V_ap_vld, ref_q_V_ap_vld)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ref_q_V_ap_vld = ap_const_logic_0) or (ref_i_V_ap_vld = ap_const_logic_0) or (x_V_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, x_V_ap_vld, ref_i_V_ap_vld, ref_q_V_ap_vld)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ref_q_V_ap_vld = ap_const_logic_0) or (ref_i_V_ap_vld = ap_const_logic_0) or (x_V_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, x_V_ap_vld, ref_i_V_ap_vld, ref_q_V_ap_vld, ret_V_fu_36_p2, ap_return_0_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ref_q_V_ap_vld = ap_const_logic_0) or (ref_i_V_ap_vld = ap_const_logic_0) or (x_V_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_0 <= ret_V_fu_36_p2;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, x_V_ap_vld, ref_i_V_ap_vld, ref_q_V_ap_vld, ret_V_1_fu_46_p2, ap_return_1_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ref_q_V_ap_vld = ap_const_logic_0) or (ref_i_V_ap_vld = ap_const_logic_0) or (x_V_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_1 <= ret_V_1_fu_46_p2;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;

        lhs_V_fu_28_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_V),16));


    ref_i_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ref_i_V_ap_vld)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ref_i_V_blk_n <= ref_i_V_ap_vld;
        else 
            ref_i_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ref_q_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ref_q_V_ap_vld)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ref_q_V_blk_n <= ref_q_V_ap_vld;
        else 
            ref_q_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ret_V_1_fu_46_p0 <= ref_q_V;
    ret_V_1_fu_46_p1 <= lhs_V_fu_28_p1(8 - 1 downto 0);
    ret_V_1_fu_46_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(ret_V_1_fu_46_p0) * signed(ret_V_1_fu_46_p1))), 16));
    ret_V_fu_36_p0 <= ref_i_V;
    ret_V_fu_36_p1 <= lhs_V_fu_28_p1(8 - 1 downto 0);
    ret_V_fu_36_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(ret_V_fu_36_p0) * signed(ret_V_fu_36_p1))), 16));

    x_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, x_V_ap_vld)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_V_blk_n <= x_V_ap_vld;
        else 
            x_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

end behav;
