# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/work/radar_course/lesson_2/vivado/arty_hw/arty_hw.srcs/sources_1/bd/dds_sys/ip/dds_sys_dds_compiler_0_0/dds_sys_dds_compiler_0_0.xci
# IP: The module: 'dds_sys_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/radar_course/lesson_2/vivado/arty_hw/arty_hw.srcs/sources_1/bd/dds_sys/ip/dds_sys_dds_compiler_0_0/dds_sys_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_sys_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/work/radar_course/lesson_2/vivado/arty_hw/arty_hw.srcs/sources_1/bd/dds_sys/ip/dds_sys_dds_compiler_0_0/dds_sys_dds_compiler_0_0.xci
# IP: The module: 'dds_sys_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/radar_course/lesson_2/vivado/arty_hw/arty_hw.srcs/sources_1/bd/dds_sys/ip/dds_sys_dds_compiler_0_0/dds_sys_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_sys_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
