webtalk_init -webtalk_dir D:/work/radar_course/lesson_4/vivado/iq_decimate/iq_decimate.sim/sim_1/behav/xsim/xsim.dir/sys_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec  2 18:31:33 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2615518" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9c457efb-2f68-40f7-a4e0-296f8a2241c8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "72b0500a20794258aa3e5e56af12c52f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "201 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "8.86_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16656_KB" -context "xsim\\usage"
webtalk_transmit -clientid 783480088 -regid "" -xml D:/work/radar_course/lesson_4/vivado/iq_decimate/iq_decimate.sim/sim_1/behav/xsim/xsim.dir/sys_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/work/radar_course/lesson_4/vivado/iq_decimate/iq_decimate.sim/sim_1/behav/xsim/xsim.dir/sys_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/work/radar_course/lesson_4/vivado/iq_decimate/iq_decimate.sim/sim_1/behav/xsim/xsim.dir/sys_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
