# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/dds_sys/dds_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_sys || ORIG_REF_NAME==dds_sys} -quiet] -quiet

# IP: bd/dds_sys/ip/dds_sys_dds_compiler_0_0/dds_sys_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_sys_dds_compiler_0_0 || ORIG_REF_NAME==dds_sys_dds_compiler_0_0} -quiet] -quiet

# IP: bd/dds_sys/ip/dds_sys_controller_dds_0_0/dds_sys_controller_dds_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_sys_controller_dds_0_0 || ORIG_REF_NAME==dds_sys_controller_dds_0_0} -quiet] -quiet

# IP: bd/dds_sys/ip/dds_sys_vio_0_0/dds_sys_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_sys_vio_0_0 || ORIG_REF_NAME==dds_sys_vio_0_0} -quiet] -quiet

# IP: bd/dds_sys/ip/dds_sys_system_ila_0_0/dds_sys_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_sys_system_ila_0_0 || ORIG_REF_NAME==dds_sys_system_ila_0_0} -quiet] -quiet

# IP: bd/dds_sys/ip/dds_sys_clk_wiz_0_0/dds_sys_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_sys_clk_wiz_0_0 || ORIG_REF_NAME==dds_sys_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/dds_sys/dds_sys_ooc.xdc
